### ISSUE TITLE
Lets make a hosted version!

### ISSUE THREAD

**Issue by samouri** [zachlite/gojuki#2]
Hi @zachlite!

What would you say to the idea of making a hosted version of gojuki with improved networking?
I would love love love to be a part of the process especially if OCaml or ReasonML were involved.

**Comment by zachlite** [comment]
@samouri, thanks for your interest!
This sounds really interesting.  I'll have some bandwidth for new projects in November.  Let's revisit this then!

**Comment by samouri** [comment]
Done at a new location, https://github.com/FriteGames/gojuki/
